### PR TITLE
Separate configs and add readme

### PR DESCRIPTION
**Pull request by sarahzinger**

### CODE REVIEW

**Comment by drewcur** [comment]
Do you need to remove the `react` plugin and `jsx` lines as well?

**Comment by sarahzinger** [comment]
@drewcur yes! sorry, it has now been updated.

**Comment by drewcur** [comment]
Hmm, I think we still want the `experimentalObjectRestSpread` that was paired with the `jsx` declaration.

**Comment by sarahzinger** [comment]
Good point!

**Pull request closed without merging**
